// packages/core/src/angular/feedback-button.component.ts
import { Component, Input, OnDestroy, OnInit, effect, inject } from "@angular/core";

import { HeedKitService } from "./heedkit.service";
import { mount, type Widget } from "../index";

/**
 * Thin Angular wrapper around the shared JS widget — same rendering as the
 * other framework SDKs. The component has no template; the widget injects
 * itself into document.body via mount().
 */
@Component({
  selector: "heedkit-button",
  standalone: true,
  template: "",
})
export class FeedbackButtonComponent implements OnInit, OnDestroy {
  @Input() label?: string;
  @Input() hideLauncher = false;

  private svc = inject(HeedKitService);
  private widget: Widget | null = null;

  constructor() {
    // Mount lazily once init() resolves so the widget has the theme.
    effect(() => {
      if (this.svc.ready() && !this.widget) {
        this.widget = mount({
          projectKey: this.svc.projectKey,
          apiUrl: this.svc.apiUrl,
          user: this.svc.user,
          label: this.label,
          hideLauncher: this.hideLauncher,
        });
      }
    });
  }

  ngOnInit() {
    // Effect above handles the mount; this hook is here so the lifecycle is
    // explicit to consumers reading the class.
  }

  ngOnDestroy() {
    this.widget?.destroy();
    this.widget = null;
  }

  open() { this.widget?.open(); }
  close() { this.widget?.close(); }
}

// packages/vue/src/FeedbackButton.vue
<script setup lang="ts">
// Thin Vue wrapper that imperatively mounts the shared JS widget. Keeps every
// SDK rendering the same UI without duplicating widget code per framework.
import { inject, onBeforeUnmount, onMounted, watch } from "vue";

import { HEEDKIT_KEY, type HeedKitInjection } from "./plugin";
import { mount, type Widget } from "@heedkit/sdk-js";

const props = defineProps<{
  label?: string;
  hideLauncher?: boolean;
}>();

const fh = inject<HeedKitInjection>(HEEDKIT_KEY);
if (!fh) throw new Error("Install the HeedKit plugin first: app.use(createHeedKit(...))");

let widget: Widget | null = null;

function ensureMounted() {
  if (widget) return;
  widget = mount({
    projectKey: fh!.projectKey,
    apiUrl: fh!.apiUrl,
    user: fh!.user,
    label: props.label,
    hideLauncher: props.hideLauncher,
  });
}

// `ready` flips once init() resolves — mount then so the theme is available.
watch(() => fh.ready.value, (ready) => {
  if (ready) ensureMounted();
}, { immediate: true });

onMounted(() => {
  if (fh.ready.value) ensureMounted();
});

onBeforeUnmount(() => {
  widget?.destroy();
  widget = null;
});

defineExpose({
  open: () => widget?.open(),
  close: () => widget?.close(),
});
</script>

<template>
  <!-- The widget renders into document.body via mount(); this component has no
       template content of its own. -->
</template>
